### PR TITLE
Update com.oxygenxml.json.dita.json to work with latest DITA OT versions

### PR DESCRIPTION
**Pull request by raducoravu**
## Description
Small changes to Java code in order to make plugin work with DITA OT 4.x.

### CODE REVIEW

**Comment by jelovirt** [comment]
Sign-off is missing and the hash hasn't been updated so it doesn't match the new URI. Preferably you could keep the old version metadata and add a new version

**Comment by raducoravu** [comment]
@jelovirt I updated the checksum and added a signoff on my second commit.
Btw I'm using "CatalogUtils.getCatalogResolver()" in my JSON parser code:
https://github.com/oxygenxml/dita-json/blob/master/com.oxygenxml.json.dita/src/com/oxygenxml/json/dita/JSONReader.java
Does this mean that after your latest changes this method will disappear as it was moved to the XML utilities class? Or did you leave it deprecated?

**Comment by jelovirt** [comment]
> I updated the checksum and added a signoff on my second commit.

You have to add a sign-off to every commit. I suggest you squash the commits into one and make sure that has the sign-off.

**Comment by raducoravu** [comment]
@jelovirt thinking that the "com.oxygenxml.json.dita.json" plugin is more of a build-your-own thing where people need to edit an XSLT stylesheet in order to obtain the proper DITA XML topic that they want to obtain from the JSON content, maybe the proper thing to do would be for me to close this pull request and open another one in which I remove the plugin from the registry which should in general keep plugins which are usable as they are or which define parameters to customize them, not plugins which require editing content inside the plugin folder.

**Pull request closed without merging**
