### PR TITLE
Released 2.0.0, correct dep version for 1.0.0

### PR DESCRIPTION
**Pull request by drmacro**
Signed-off-by: Eliot Kimber <ekimber@contrext.com>

### CODE REVIEW

**Comment by jelovirt** [comment]
@drmacro Could you check the code, Travis validation failed with incorrect checksum.

**Comment by drmacro** [comment]
I downloaded both release packages from github using the URLs in the JSON and reran shasum and got the same values as in the JSON file I submitted, so not sure why the 1.0.0 checksum check failed:
```
ekimber@Mako[feature/dci18n]$ shasum -a 256 "/Users/ekimber/Downloads/org_dita-community_i18n_plugin_1.0.0 (2).zip" 
a89ca0d79a4d891785a768729d6b76dd2c6632c5d38901b0cd536e55491d8ed0  /Users/ekimber/Downloads/org_dita-community_i18n_plugin_1.0.0 (2).zip
```

**Comment by drmacro** [comment]
Does the reported fix to the registry PR generation allow this PR to be merged or do I need to resubmit it?

**Comment by jelovirt** [comment]
Testing this manually

```bash
➜  tmp curl -OL https://github.com/dita-community/org.dita-community.i18n/releases/download/version-2.0.0/org_dita-community_i18n_plugin_2.0.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630    0   630    0     0   1773      0 --:--:-- --:--:-- --:--:--  1774
100 2205k  100 2205k    0     0  1167k      0  0:00:01  0:00:01 --:--:-- 1576k
➜  tmp shasum -a 256 org_dita-community_i18n_plugin_2.0.0.zip
335546cdcc60ba42020acf08be7dd3df067456b5f32bab5a252e4fe7fff9bf48  org_dita-community_i18n_plugin_2.0.0.zip
```

Which is weird, because checksum on the JSON file is `335546cdcc60ba42020acf08be7dd3df067456b5f32bab5a252e4fe7fff9bf48`.

**Pull request closed without merging**
